# =========================================================
# AizenSMP - Spawn Hub
# =========================================================

options:
    prefix: &6[&eAizenSMP&6] &r

command /spawn:
    trigger:
        if {aizensmp.spawn.location} is not set:
            send "%{@prefix}% &cSpawn has not been set yet." to player
            stop
        teleport player to {aizensmp.spawn.location}
        send "%{@prefix}% &aTeleported to spawn." to player

on join:
    if {aizensmp.spawn.location} is set:
        teleport player to {aizensmp.spawn.location}
